// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP2WdsLXBu-JjTfFQLymM2D8A7X7ImabU',
    appId: '1:447261760009:web:82be393dea69edcd5236d8',
    messagingSenderId: '447261760009',
    projectId: 'shreddit-ede6e',
    authDomain: 'shreddit-ede6e.firebaseapp.com',
    storageBucket: 'shreddit-ede6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzgAKteYTMJLM27wB-WJI1byMz2UdoRI',
    appId: '1:447261760009:android:26ed1ac77e6738a85236d8',
    messagingSenderId: '447261760009',
    projectId: 'shreddit-ede6e',
    storageBucket: 'shreddit-ede6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx6nmPbHvuS62cHf0RyurOacDvImQdP6Q',
    appId: '1:447261760009:ios:986b0fa783ae39a05236d8',
    messagingSenderId: '447261760009',
    projectId: 'shreddit-ede6e',
    storageBucket: 'shreddit-ede6e.appspot.com',
    iosClientId: '447261760009-b6t607k40bhve8jt3unve2od2r1k7ics.apps.googleusercontent.com',
    iosBundleId: 'com.example.shreddit',
  );
}
